runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: Profil/profil.html
  upload: Profil/profil.html

- url: /(.*)
  static_files: Profil/\1
  upload: Profil/(.*)
